### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [anushkrishnav/anushkrishnav#3]
[Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

**Comment by anushkrishnav** [comment]
@VasudevJaiswal  ??

**Comment by VasudevJaiswal** [comment]
> [Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

Plz Check Again

**Comment by anushkrishnav** [comment]
@VasudevJaiswal No one will click on links  when there is no text available if you are inviting someone to your org care enough to leave an invite instead of just link.

**Comment by VasudevJaiswal** [comment]
> > [Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)
> 
> Plz Check Again

Check again

**Comment by VasudevJaiswal** [comment]
Check your email

**Comment by anushkrishnav** [comment]
I was talking about the reason why you want me to join your org , also how do you know me ? Bro before inviting someone give them a reason or at least ask them to join just adding them to org or saying click here is disrespect

**Comment by Vyvy-vi** [comment]
I'm so sorry that you're receiving this spam @anushkrishnav :(
This person spammed many members in EddieHub's github org. with links to join this org.
